---
repos:
  - repo: local
    hooks:
      - id: reject-keepassxc-keeshare
        name: Reject KeeShare-enabled KeePassXC config
        args:
          - --content=[KeeShare]
        entry: bash scripts/reject-on-content.sh
        files: keepassxc\.ini$
        language: system
        pass_filenames: true
